version: '3.8'
services:
  # Spring Boot Application
  app:
    image: annual-report-manager:latest
    container_name: annual-report-manager
    build:
      context: ../annual-report-manager
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data/incoming
    environment:
        - "COD_DIRECTORY=/data/incoming"
        - "COD_FILEFORMAT=csv"
        - "COD_BATCHSIZE=100"
        - "COD_REPORT=/data/report"
    networks:
      - elk
    depends_on:
      - db

  # Mysql Database
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: secretWallet
      MYSQL_DATABASE: wallet
    ports:
      - "3306:3306"
    volumes:
      - ../database/init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ../database/schema.sql:/docker-entrypoint-initdb.d/02_schema.sql
      - ../database/functions.sql:/docker-entrypoint-initdb.d/03_functions.sql
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  esdata:
    driver: local
