version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: secretWallet
      MYSQL_DATABASE: wallet
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./schema.sql:/docker-entrypoint-initdb.d/02_schema.sql
      - ./functions.sql:/docker-entrypoint-initdb.d/03_functions.sql
    networks:
      - dbnetwork

networks:
  dbnetwork:
    driver: bridge
