version: '3.8'
services:
  postgres:
    build: .
    container_name: postgres-db
    environment:
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: secretWallet
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./schema.sql:/docker-entrypoint-initdb.d/02_schema.sql
      - ./functions.sql:/docker-entrypoint-initdb.d/03_functions.sql
    networks:
      - pgnetwork

networks:
  pgnetwork:
    driver: bridge
