# Use the official MySQL image from Docker Hub
FROM mysql:latest

# Set environment variables for MySQL root user
ENV MYSQL_ROOT_PASSWORD=secretWallet
ENV MYSQL_DATABASE=wallet

# Expose the default MySQL port
EXPOSE 3306